### ISSUE TITLE
Issue with Running Application in content-web folder

### ISSUE THREAD

**Issue by PraveenAnil** [Microsoft/MCW-Containers-and-DevOps#21]
I am getting a syntax error with error message: 

> "Identifier 'contentApiUrl' has already been declared"
[Screenshot 1](https://github.com/PraveenAnil/images/raw/master/issue1.png)
[Screenshot 2](https://github.com/PraveenAnil/images/raw/master/issue2.png)
 when executing "nodejs ./server.js &" command given  in Exercise 1-> Task 1 -> Step 13

**Comment by rbmathis** [comment]
The fix for this is to comment the line 11 in /data-access/index.js (where contentApiUrl is declared as 
`const contentApiUrl = "http://localhost:3001";`
additional info: The file probably needs a bit of cleanup, the var contentApiUrl is declared 4 times, and 2 of them are already commented, leaving 2 delcarations of the same var which causes the parser to barf.

**Comment by jamesrcounts** [comment]
I updated the tarball with the starter files, we will need to update the bitly to close the loop.
