### ISSUE TITLE
Use of Vi/Vim 🤯

### ISSUE THREAD

**Issue by benc-uk** [Microsoft/MCW-Containers-and-DevOps#70]
I'm shocked (putting it mildly) that in 2019 we're asking people to edit code using Vi/Vim

- Why Vi/Vim and not Nano, which is a much, much MUCH more friendly editor!
- It's madness asking them to **TYPE IN** a Dockerfile rather than copy & paste it
- Why not use the Azure DevOps Repos web UI to create/edit the files? You can create new files there, paste into the web file editor. Then commit and do a pull on the build VM

I'll admit creating code & files directly into the repo using the web UI is a little unorthodox, but it's no less strange than asking people to use Vi !

**Comment by waltermyersiii** [comment]
Ben, I support using Nano instead of Vi/Vim. I do think they should gain the experience of typing in a Dockerfile. That's part of the learning and that's how I learned it.

**Comment by jamesrcounts** [comment]
@waltermyersiii I agree that typing some of the files are part of the learning process.  

Not sure I feel strongly about keeping or removing vim.  Vim is a reality.  People looking to learn these topics are going to have to deal with Vim eventually.

Having said that, I didn't pick Vim, it was there in early drafts before I started working on this lab.  Today, my main concern about switching to Nano would be throwing a late-breaking request to a team that is already in the middle of a revision for the changes in #66, focused on bringing in new content and on making sure the instructions/screenshots are up to date for Azure and Azure DevOps.

Putting timing aside, if we *were* to revisit the choice of editor I think I would want to look at some combination of using the cloud shell more as @benc-uk suggested in #42 and using VS Code for editing locally.  The earliest versions of this lab that I was involved with didn't use any kind of hosted git repo, so editing on the remote machine made a certain kind of sense.  We've had Azure DevOps in the mix since the 2018 revision and we could look at doing less work on the "build agent" now.

**Comment by benc-uk** [comment]
Less work on build agent is a good idea, creating the Dockerfile via the git repo and pulling changes down would be a lot more real world way of working

Moving to Cloud Shell also another excellent idea

I also appreciative the timing might not be great, just something to consider for future updates

**Comment by waltermyersiii** [comment]
@jamesrcounts, let's go ahead and stick with Vim. There's enough other stuff to worry about. We can look at Cloud Shell for the future, but that would also mean storing variables in case the session is interrupted, which is a bit of a pain. Still, it's promising and I'm sure they will eventually provide that automatically.

Definitely VS Code for editing locally.

**Comment by DawnmarieDesJardins** [comment]
Closing issue, addressed in March 2019 update
